[ACCOUNT-2595/2604] feat: create & verify shop identity
PrestaShopCorp/ps_accounts pull request #433
Opened 2024-09-04 09:33 UTC by atourneriePresta

- [ ] test: execInShopContext vs frontendUrl bug & shop_id;
- [ ] test: ShopProvider::getBackendUrl, getFrontendUrl;
- [ ] update OAuthClients setting redirect uris with and without `index.php`
- [ ] Refactor DEBUG controller & ActionShopAccountUnlinkAfter

2024-09-06 07:50 UTC, hschoenenberger requested changes

2024-09-06 07:50 UTC, hschoenenberger commented on src/Account/CommandHandler/AbstractClass/GetShopAbstract.php
> +class GetShopAbstract
```suggestion
class MultiShopHandlerAbstract
```
For a parent class name you have to be more generic as this class will probably contain more than just this.

2024-09-06 07:50 UTC, hschoenenberger commented on src/Api/Client/AccountsClient.php
> +    public function createOauth2Client($backOfficeUrl, $frontendUrl, $multiShopId) {
```suggestion
    public function createShopIdentity($backOfficeUrl, $frontendUrl, $multiShopId) {
```
I guess Mr. Tournerie as many "to_dip_into_the_yoghurt" in its kitchen. Personally I use "spoons" :trollface:

2024-09-06 07:50 UTC, hschoenenberger commented on src/Service/PsAccountsService.php
> -        $linkShop = $this->module->getService(LinkShop::class);
Maybe we should just delete this method

2024-09-06 07:50 UTC, hschoenenberger commented on src/Account/Command/Oauth2InstallCommand.php
> +class Oauth2InstallCommand
Let's use a more meaningful name related to the identity creation maybe ?

2024-09-06 08:55 UTC, hschoenenberger commented on src/Account/CommandHandler/Oauth2InstallHandler.php
> +                    $this->configRepo->updateShopUuid($resp['body']['cloudShopId']);
Don't use directly config repo when there are dedicated classes for this

2024-09-10 07:38 UTC, atourneriePresta commented on src/Service/PsAccountsService.php
> -        $linkShop = $this->module->getService(LinkShop::class);
I think we can

2024-09-13 14:55 UTC, hschoenenberger requested changes

2024-09-13 14:55 UTC, hschoenenberger commented on config/command.yml
> +    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\Oauth2InstallMultiHandler
```suggestion
  PrestaShop\Module\PsAccounts\Account\CommandHandler\MultiCreateIdentityHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\MultiCreateIdentityHandler
```

2024-09-13 14:55 UTC, hschoenenberger commented on config/command.yml
> +    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\Oauth2InstallHandler
```suggestion
  PrestaShop\Module\PsAccounts\Account\CommandHandler\CreateIdentityHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\CreateIdentityHandler
```

2024-09-17 14:13 UTC, hschoenenberger commented on ps_accounts.php
> +        $commandBus->handle(new \PrestaShop\Module\PsAccounts\Account\Command\MultiCreateIdentityCommand([]));
Can you confirm the idempotency of that call ?

2024-10-16 09:27 UTC, antoinemetifeu commented on src/Account/CommandHandler/CreateIdentityHandler.php
> +        if (!$this->oauth2Client->exists()) {
I think it's better to invert this condition and apply the return early pattern. For me, it's more readable to read a code without much imbrication or _else_ clause

2025-04-29 08:40 UTC, antoinemetifeu commented on controllers/admin/AdminAjaxPsAccountsController.php
> +//            ));
to remove ?

2025-04-29 08:40 UTC, antoinemetifeu commented on controllers/front/apiV2ShopHealthCheck.php
>  //            'shop.health',
To remove ? It's assert directly on the abstract class and getAudience / getScope methods ?

2025-04-29 08:40 UTC, antoinemetifeu commented on src/Account/ProofManager.php
> +        $proof = Uuid::uuid4()->toString();
:eyes:

2025-04-29 08:40 UTC, antoinemetifeu commented on src/Account/Command/CheckStatusCommand.php
> +class CheckStatusCommand
It's more a Query than a Command, no?

2025-04-29 08:40 UTC, antoinemetifeu commented on src/Service/PsAccountsService.php
> +        return $this->statusManager->identityCreated();
question : for compat, modules using ps_accounts actually know they can retrieve shop and user tokens when "isAccountLinked" ?

2025-04-29 08:59 UTC, hschoenenberger commented on ps_accounts.php
> +        'displayAdminAfterHeader',
```suggestion
        'displayAdminAfterHeader', // FIXME: UX for alpha version only
```

2025-04-29 09:00 UTC, hschoenenberger commented on ps_accounts.php
> +//function ps_accounts_fix_upgrade()
remove thoses comments

2025-04-29 09:15 UTC, hschoenenberger commented on src/Account/CommandHandler/DeleteUserShopHandler.php
>                  $ownerToken->getJwt()
Voir à migrer vers des AccessToken

2025-04-29 12:07 UTC, hschoenenberger commented on src/Account/CommandHandler/UpdateUserShopHandler.php
>          $this->ownerSession = $ownerSession;
IDEM commentaire précédent, migrer sur des routes compatibles AccessToken hydra.
Ne plus utiliser les tokens Firebase en interne avec ps_accounts.

2025-04-29 12:55 UTC, hschoenenberger commented on src/Account/CommandHandler/VerifyIdentityHandler.php
> +     * @throws AccountsException
Should we let thoses exception bubble or catch them inside handler.

2025-04-29 13:07 UTC, hschoenenberger commented on src/Account/ProofManager.php
> +        //$proof = base64_encode(\hash_hmac('sha512', Uuid::uuid4()->toString(), uniqid()));
accounts-api is checking for `uuid` type

2025-04-29 13:13 UTC, hschoenenberger commented on src/Account/ProofManager.php
> +    public function getProof()
Add a setter to clean proof at the end of the verification flow

2025-04-29 13:31 UTC, hschoenenberger commented on src/Account/ShopUrl.php
> +<?php
Try to dediplicate with the ShopProvider code

2025-04-29 13:33 UTC, hschoenenberger commented on src/Account/StatusManager.php
> +    public function getOwnerUuid($refresh = false)
```suggestion
    public function getPointOfContactUid($refresh = false)
```

2025-04-29 13:36 UTC, hschoenenberger commented on src/Account/StatusManager.php
> +    public function getOwnerEmail($refresh = false)
```suggestion
    public function getPointOfContactEmail($refresh = false)
```

2025-04-29 13:51 UTC, hschoenenberger commented on src/Hook/ActionObjectShopUpdateAfter.php
>          } catch (Exception $e) {
Throwable ?

2025-04-29 13:54 UTC, hschoenenberger commented on src/Hook/ActionShopAccountUnlinkAfter.php
>  class ActionShopAccountUnlinkAfter extends Hook
Put this code elsewhere and remove that hook

2025-04-29 13:57 UTC, hschoenenberger commented on src/Http/Controller/AbstractRestController.php
>      protected function decodePayload($defaultShopId = null)
merge with AbstractV2RestController

2025-04-29 13:58 UTC, hschoenenberger commented on src/Presenter/PsAccountsPresenter.php
> +    protected $shopIdentity;
```suggestion
    protected $statusManager;
```

2025-04-29 14:07 UTC, hschoenenberger commented on src/enforce_autoload.php
> +<?php
Remove that code

2025-04-29 14:52 UTC, hschoenenberger commented on src/Account/Command/CheckStatusCommand.php
> +class CheckStatusCommand
I removed the command

2025-04-29 14:55 UTC, hschoenenberger commented on src/Account/ProofManager.php
> +        $proof = Uuid::uuid4()->toString();
accounts-api validation also needs to be updated consequently

2025-04-30 07:06 UTC, hschoenenberger commented on src/Service/PsAccountsService.php
> +        return $this->statusManager->identityCreated();
Good question, to be discussed.

2025-05-21 08:34 UTC, antoinemetifeu commented on src/Account/CommandHandler/VerifyIdentityHandler.php
> +     * @throws AccountsException
It's better to let exception bubbles up, but it can't be risky in a PrestaShop module if these exceptions are not caught above.

And we can try them in the handler, if we have some logic to apply when one of these exceptions are throwed.

2025-05-21 12:43 UTC, antoinemetifeu commented on src/Account/StatusManager.php
> +        return $this->getCachedStatus();
Some attention here. If we have a problem with `setCachedStatus` or a`ccountsService->shopStatus()`, we return indefinely the cached cache

2025-06-05 14:09 UTC, merged